# Generated by Django 3.0.8 on 2020-07-16 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='listing',
            new_name='listing_name',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='listing',
            new_name='listing_name',
        ),
    ]
