# Generated by Django 3.0.8 on 2020-07-17 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_closed_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closed_listing',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='auctions.Bid'),
        ),
    ]
