# Generated by Django 3.0.8 on 2020-07-20 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Closed_listing',
        ),
    ]
